const UPDATE_MESSAGES = "UPDATE_MESSAGES";
const NEW_MESSAGE = "NEW_MESSAGE";
const POST_MESSAGE = "POST_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";
const UPDATE_LIST = "UPDATE_LIST";
const POST_PRODUCT = "POST_PRODUCT";
const NEW_PRODUCT = "NEW_PRODUCT";

module.exports = {
    UPDATE_MESSAGES,
    NEW_MESSAGE,
    POST_MESSAGE,
    LIKE_MESSAGE,
    UPDATE_LIST,
    POST_PRODUCT,
    NEW_PRODUCT,
};
